Document: libosal
Title: Debian libosal Manual
Author: <insert document author here>
Abstract: This manual describes what libosal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libosal/libosal.sgml.gz

Format: postscript
Files: /usr/share/doc/libosal/libosal.ps.gz

Format: text
Files: /usr/share/doc/libosal/libosal.text.gz

Format: HTML
Index: /usr/share/doc/libosal/html/index.html
Files: /usr/share/doc/libosal/html/*.html
