name: Build gh-pages

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen build-essential devscripts debhelper autotools-dev autoconf-archive fakeroot sed git python3-pip python3-venv curl jq
      
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mark working directory as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Build gh-pages
        env: 
          BUILDDIR: docs
          GH_PAGES_DIR_NAME: gh-pages
        run: |
          safe_branch=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          DOCS=${GH_PAGES_DIR_NAME}/${safe_branch}
          rm -rf "${GH_PAGES_DIR_NAME}"
          git clone `git config --get remote.origin.url` --branch gh-pages --depth 1 gh-pages
          install -d ${BUILDDIR}
          rm -rf "${BUILDDIR}/html"
          rm -rf "${DOCS}"
          doxygen doxygen.cfg
          touch "${BUILDDIR}/html/.nojekyll"
          mv "${BUILDDIR}/html" $(DOCS)
          cd "${GH_PAGES_DIR_NAME}" && python3 ../docs/create_directory_listing.py
          # add updated branch listing
          cp $(BUILDDIR)/*.css ${GH_PAGES_DIR_NAME}/
          cp $(BUILDDIR)/index.html ${GH_PAGES_DIR_NAME}/
          git -C ${GH_PAGES_DIR_NAME} config user.name "Robert Burger"
          git -C ${GH_PAGES_DIR_NAME} config user.email "robert.burger@dlr.de"
          git -C ${GH_PAGES_DIR_NAME} add index.html
          git -C ${GH_PAGES_DIR_NAME} add content.html
          git -C ${GH_PAGES_DIR_NAME} add navtree.css
          git -C ${GH_PAGES_DIR_NAME} add main.css
          git -C ${GH_PAGES_DIR_NAME} add "${safe_branch}/*"
          -git -C ${GH_PAGES_DIR_NAME} commit -m 'Automatic update of GH pages'
          # The pipeline has to lock the execution of this script, so no updates of the branch are done since clone.
          git -C ${GH_PAGES_DIR_NAME} push

